### ISSUE TITLE
Viimeistely ToDo

### ISSUE THREAD

**Issue by dominooooooo** [dominooooooo/Retele.fi#6]
- [ ] muokkaa kuitti suomeksi
- [ ] varmista että sähköpostissa on vain kuitti, ei laskua
- [x] varmista että tuote päivittyy livemodessa
- [x] varmista että automaattinen kuitin lähetys toimii
- [x] toimitustapojen varmistus
- [x] tuote poistuu oston jälkeen ?
- [x] kysy lisää toimimaan
- [x] optimoi ja viimeistele koodia
- [x] palaa etusivulle painike tilausvahvistukseen
